name: Run binary in different java versions

on:
  workflow_dispatch:
    inputs:
      project:
        required: true
      requested_task_goal:
        required: true
      tags:
        required: true

jobs:
  build:
    strategy:
      matrix:
        java: [11]

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version:  ${{ matrix.java }}

      - name: Prepare a build with nowinandroid
        run: |
          curl -L https://github.com/cdsap/TaskReport/releases/download/v.0.2.0/taskreport --output taskreport
          chmod 0757 taskreport
           #./taskreport --max-builds=5000 --project=build-validation-scripts --requested-task=build --task-path=:shellcheckGradleScripts --single-task --tags=ci --api-key=${{ secrets.GE_API_KEY }} --url=${{ secrets.GE_URL }}
          ./taskreport --max-builds=5000 --project=${{ github.event.inputs.project }} --requested-task=${{ github.event.inputs.requested_task_goal }} --tags=${{ github.event.inputs.requested_task_goal }} --api-key=${{ secrets.GE_API_KEY }} --url=${{ secrets.GE_URL }}
        uses: actions/upload-artifact@v3
        with:
          name: csv
          path: |
            ./*_*.csv
            ./duration_*.png
