name: Execute TaskReport

on:
  workflow_dispatch:
    inputs:
      type_report:
        type: choice
        options:
          - general
          - single-task
        required: true
      project:
        required: true
      requested_task_goal:
        required: true
      tags:
        required: true
      task_path:
          description: For Single Task reports you need to include the task path under investigation (only Gradle Builds)
          required: false

jobs:
  build:
    strategy:
      matrix:
        java: [11]

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version:  ${{ matrix.java }}

      - name: Prepare a report for ${{ github.event.inputs.project }}-${{ github.event.inputs.requested_task_goal }}
        run: |
          curl -L https://github.com/cdsap/TaskReport/releases/download/v.0.2.4/taskreport --output taskreport
          chmod 0757 taskreport
          if [ ${{ github.event.inputs.type_report }} == "general" ]; then ./taskreport --max-builds=50 --project=${{ github.event.inputs.project }} --requested-task=${{ github.event.inputs.requested_task_goal }} --tags=${{ github.event.inputs.tags }} --api-key=${{ secrets.GE_API_KEY }} --url=${{ secrets.GE_URL }} ; fi
          if [ ${{ github.event.inputs.type_report }} == "single-task" ]; then ./taskreport --max-builds=50 --project=${{ github.event.inputs.project }} --requested-task=${{ github.event.inputs.requested_task_goal }} --single-task --task-path=${{ github.event.inputs.task_path }} --tags=${{ github.event.inputs.tags }} --api-key=${{ secrets.GE_API_KEY }} --url=${{ secrets.GE_URL }} ; fi
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.type_report }}-${{ github.event.inputs.project }}-${{ github.event.inputs.requested_task_goal }}-outputs
          path: |
            ./*_*.csv
            ./duration_*.png
